### ISSUE TITLE
Release Plan for 4.4

### ISSUE THREAD

**Issue by nvoxland** [liquibase/liquibase#1797]
This plan captures our work for **4.4.0**. We are planning to **ship it in late April.**

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark          | Description      |
|----|----|
| :runner:      | on-going work    |
| :raised_hand:      | blocked task    |
| :muscle:      | stretch goal for this release    |
| :red_circle:  | missing issue reference    |
| :large_blue_circle:   | more investigation required to remove uncertainty     |
| :black_circle:  | under discussion within the team     |
| ⬛ | a large work item, larger than one iteration    |

## Configuration API
* [x]  Improve liquibase.configuration API and maintain backwards compatibility #1692 

## Command API
* [x] Improve liquibase.command API and maintain backwards compatibility #1708 

## New CLI
* [x] Create new CLI code that leverages the new configuration and command APIs to provide the option for extensions to add new commands dynamically as well as be more user-friendly #1702

**Comment by RajarsiGit** [comment]
Hi, Liquibase Team, when shall we get to use the latest version v4.4.0?

**Comment by molivasdat** [comment]
Hi @RajarsiGit , we missed our plan to ship in April as it states at the top of this page.  May is new target.

**Comment by molivasdat** [comment]
@RajarsiGit 4.4.0 has hit maven central.

**Comment by RajarsiGit** [comment]
@molivasdat grey! Thanks for notifying. Congrats to Liquibase Team for this update
